columns:
  name: string
  description: text
  price: string
  quantity: string
  quantity_items: string
  options:
    type: text
    nullable: true
  images:
    type: string
    nullable: true
  physical:
    type: boolean
    default: false

relationships:
  - Store

seeds:
  count: 5
  truncate: true
  data:
    name: '@faker.name'
    identifier: '@faker.uuid'
    verified_at: '@tick.format:YYYY-MM-DD HH:mm:ss'
