columns:
  name: string
  description: text
  price: string
  quantity: string
  quantity_items: string
  options:
    type: text
    nullable: true
  images:
    type: json
    nullable: true
  categories:
    type: json
    nullable: true
  physical:
    type: boolean
    default: false
    nullable: true
  status:
    type: enum
    default: active
    values:
      - active
      - archived

relationships:
  - Store

seeds:
  count: 5
  truncate: true
  data:
    name: '@faker.name'
    slug: '@faker.uuid'
    verified_at: '@tick.format:YYYY-MM-DD HH:mm:ss'
