# fly.toml app configuration file generated for selll on 2025-03-22T21:20:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'selll'
primary_region = 'lhr'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[env]
APP_ENV = 'production'
APP_DEBUG = 'true'
APP_URL = 'https://selll.online/'
DB_CONNECTION = 'pgsql'
DB_DATABASE = 'selll'
ANALYTICS_DB_DATABASE = 'analytics'
IMPORTS_DB_DATABASE = 'imports'
ANALYTICS_DB_USERNAME = 'analytics_owner'
IMPORTS_DB_USERNAME = 'imports_owner'
DB_PORT = '5432'
ANALYTICS_DB_PORT = '5432'
IMPORTS_DB_PORT = '5432'
REDIS_SESSION = 'true'
REDIS_PORT = '6379'

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
